#FROM ubuntu:18.04
#RUN sudo apt update 2>/dev/null | grep packages | cut -d '.' -f 1 
#RUN apt upgrade -y
#RUN apt install -y wget

FROM php:8.0-apache
RUN apt-get update \
 && apt-get install wget unzip zip -y




